export const en = {
    lang: "en",
    name: "Maamoun Grissa",
    job: "FullStack Web Developer",
    age: 33,
    phone: "+21650870256",
    email: "grissa.maamoun@gmail.com",
    intro: "Innovative Full Stack Web Developer with 4 years of experience in websites, web & mobile applications design and coding. Demonstrated talent for frontend and backend web development to optimize online presence. A seasoned expert in HTML, CSS, JavaScript, PHP,  MySQL, MongoDB, NodeJs, ReactJs, NextJs, VueJs, ReactNative, Ionic Framework ...",
    linkedin: "maamoun-grissa",
    facebook: "maamoung",
    instagram: "gmaamoun",
    cv: "MaamounGrissa-Resume-Fevrier22-EN.pdf",
    education: [
        {
            logo: "iset.jpg",
            certificate: "Applied license in multimedia and web development",
            institute: "Higher institute of technological studies, Sousse, Tunisia",
            date: "2007 - 2011",
        },
        {
            logo: "iset.jpg",
            certificate: "Cisco certificate : home & small business networking",
            institute: "Higher institute of technological studies, Sousse, Tunisia",
            date: "2009 - 2010",
        },
    ],
    experience: [
        {
            logo: "squadio.png",
            desc: "Frontend Web Developer at Squadio, Saudi Arabia (Remote)",
            mission: "Missions: Development & support web applications - ReactJS - Redux - Laravel ...",
            date: "2021 - Today",
        },
        {
            logo: "anytime.png",
            desc: "Manager at Anytime & Anywhere",
            mission: "Services: Development of static websites, e-commerce platforms, web and mobile applications, Graphic Design, Companies identity, Digital Marketing, SEO ...",
            date: "2021 - Today",
        },
        {
            logo: "freelancer.png",
            desc: "Web developer at Freelancer & Upwork, Internet, (Remote)",
            mission: "Mission : Development of websites, web and mobile applications : - E-commerce plateforms using opencart cms & VueJS. - Catalog & Portfolio websites using Wordpress cms & VueJs. - Web & Mobile app using React JS & React Native + Api using Laravel 8 & Livewire 2 & Tailwindcss & AlpineJs.",
            date: "2019 - 2021",
        },
        {
            logo: "flegri.png",
            desc: "Full-Stack Web developer at Flegrei, Moscow, Russia",
            mission: "Mission : Development of websites, web and mobile applications : - E-commerce plateforms using opencart cms. - Catalog websites using Wordpress cms. - Mobile app using Ionic-framework & Angular Js + Api : Laravel 7.",
            date: "2019 - 2021",
        },
        {
            logo: "kvantum.png",
            desc: "Full-Stack Web developer at Kvantum, Moscow, Russia, (Remote)",
            mission: "Mission : Development of websites, web and mobile applications. - Catalog websites using joomla cms. - Development of web application using Laravel 7.",
            date: "2019 - 2021",
        },
        {
            logo: "ksar.png",
            desc: "System administrator at LTI El Ksar Hotel, Sousse, Tunisia.",
            mission: "Mission : Management and maintenance of computers equipments, local networks, wifi networks, telephony, surveillance cameras, ERP system and audiovisual Manager.",
            date: "2013 - 2018",
        },
        {
            logo: "steq.png",
            desc: "Software developer at Tunisian company of equipments, Tunis, Tunisia.",
            mission: "Mission : Development of ERP Software of the company using FoxPro.",
            date: "2011 - 2012",
        },
    ],
    skills: [
        {
            groupName: "Base Skills",
            groupSkills: [
                "html.png",
                "css.png",
                "js.png",
                "php.png",
                "mysql.png",
            ]
        },
        {
            groupName: "Css Skills",
            groupSkills: [
                "sass.png",
                "tailwindcss.png",
                "alpinejs.png",
                "jquery.png",
                "bootstrap.png",
            ]
        },
        {
            groupName: "Front-end Skills",
            groupSkills: [
                "reactjs.png",
                "next.png",
                "vuejs.png",
                "reactnative.png",
                "ionic.png",
            ]
        },
        {
            groupName: "Back-end Skills",
            groupSkills: [
                "laravel.png",
                "nodejs.png",
                "wordpress.png",
                "opencart.png",
                "joomla.png",
            ]
        },
        {
            groupName: "Mern-Stack Skills",
            groupSkills: [
                "express.png",
                "mongodb.png",
                "redux.png",
                "materialui.png",
                "heroku.png",
            ]
        },
        
    ],
    portfolio: [
        {
            name: "Iber Conseils",
            photo: "iber.png",
            code: "https://github.com/MaamounGrissa/iber.git",
            url: "https://iber-conseils.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "KineDoc",
            photo: "kinedoc.png",
            code: "https://github.com/MaamounGrissa/kinedoc.git",
            url: "https://kinedocrdv.fr/",
            skills: ["reactjs", "nodejs"],
        },
        /* {
            name: "Arine Conseils",
            photo: "arine.png",
            code: "https://github.com/MaamounGrissa/aca-next.git",
            url: "https://arine-conseils.com/",
            skills: ["next", "css"],
        }, */
        {
            name: "Anytime & Anywhere",
            photo: "anytime.png",
            code: "https://github.com/MaamounGrissa/Anytime4Anywhere.git",
            url: "https://anytime4anywhere.com/",
            skills: ["reactjs", "css"],
        },
        {
            name: "Belkhairat Trading",
            photo: "bk-trading.png",
            code: "https://github.com/MaamounGrissa",
            url: "https://belkhairat-trading.com/",
            skills: ["opencart", "php"],
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            code: "",
            url: "https://vw.autodomkst.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            code: "https://github.com/MaamounGrissa/Valorant-Boosting.git",
            url: "https://valorantboosting.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            code: "https://github.com/MaamounGrissa/dnl",
            url: "https://dnl-deco.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            code: "https://github.com/MaamounGrissa/dalimarket",
            url: "https://dalimarket.tn/",
            skills: ["opencart", "tailwindcss"],
        },
        {
            name: "My Portfolio App",
            photo: "myportfolio.png",
            code: "https://github.com/MaamounGrissa/maamoun-portfolio-app",
            url: "https://maamoungrissa.me/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            code: "",
            url: "https://pro-artl.ru/",
            skills: ["opencart", "php"],
        },
        {
            name: "BJMatrix Store App",
            photo: "bjmatrix.png",
            code: "https://github.com/MaamounGrissa/bjmatrix.git",
            url: "https://bjmatrix.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Conformit App",
            photo: "conformit-vuejs.png",
            code: "https://github.com/MaamounGrissa/Conformit.git",
            url: "https://conformit-vuejs.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Wearmoon App",
            photo: "wearmoon-reactjs.png",
            code: "https://github.com/MaamounGrissa/WearMoon",
            url: "https://wearmoon-reactjs.netlify.app/",
            skills: ["reactjs", "sass"],
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            code: "https://github.com/MaamounGrissa/autodomkst",
            url: "",
            skills: ["laravel", "mysql"],
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            code: "",
            url: "https://barrist.ru/",
            skills: ["wordpress", "css"],
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            code: "",
            url: "https://volkswagen-almaty.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            code: "",
            url: "https://retail.comiten.ru/",
            skills: ["joomla", "html"],
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            code: "",
            url: "https://www.zavodskaya-plitka.ru/",
            skills: ["joomla", "css"],
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            code: "https://github.com/MaamounGrissa/Aidapraznik2020",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
            skills: ["html","jquery"],
        },
        {
            name: "Flegrei",
            photo: "flegri.png",
            code: "",
            url: "https://www.flegri.com/",
            skills: ["opencart", "html"],
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            code: "",
            url: "https://bahitgul.com/",
            skills: ["wordpress", "html"],
        },
    ],


    // Template Titles
    download_link: "Download Resume as PDF",
    education_title: "Education",
    experience_title: "Experience",
    skills_title: "Skills",
    portfolio_title: "Portfolio",
    url_btn: "Link",
    code_btn: "Code",
    contact_heading: "Send me message !",
    name_label: "Name",
    email_label: "E-mail",
    message_label: "Message",
    send_btn: "Send",
    feedback_message: "Message sent successfully !",
    error_message: "Error ! Please try again later !",
}

export const fr = {
    lang: "fr",
    name: "Maàmoun Grissa",
    job: "Développeur Web FullStack",
    age: 33,
    phone: "+21650870256",
    email: "grissa.maamoun@gmail.com",
    intro: "Développeur Web Full Stack innovant avec 4 ans d'expérience dans la conception et le codage de sites Web, d'applications Web et mobile. Talent démontré pour le développement Web frontend et backend afin d'optimiser la présence en ligne. Un expert chevronné en HTML, CSS, JavaScript, PHP, MySQL, MongoDB, NodeJs, ReactJs, NextJs, VueJs, ReactNative, Ionic Framework...",
    linkedin: "maamoun-grissa",
    facebook: "maamoung",
    instagram: "gmaamoun",
    cv: "MaamounGrissa-Resume-Fevrier22-FR.pdf",
    education: [
        {
            logo: "iset.jpg",
            certificate: "Licence appliquée en multimédia et développement web",
            institute: "Institut supérieur des études technologiques, Sousse, Tunisia",
            date: "2007 - 2011",
        },
        {
            logo: "iset.jpg",
            certificate: "Certificat Cisco : Réseautage du maisons et petites entreprises",
            institute: "Institut supérieur des études technologiques, Sousse, Tunisia",
            date: "2009 - 2010",
        },
    ],
    experience: [
        {
            logo: "squadio.png",
            desc: "Développeur Web Frontend chez Squadio, Arabie Saoudite (télétravail)",
            mission: "Missions: Développement et support des applications web - ReactJS - Redux - Laravel ...",
            date: "2021 - Présent",
        },
        {
            logo: "anytime.png",
            desc: "Directeur chez Anytime & Anywhere",
            mission: "Services : Développement de sites web statiques, de plateformes e-commerce, d'applications web et mobiles, Graphisme, Identité d'entreprises, Marketing Digital, SEO...",
            date: "2021 - Présent",
        },
        {
            logo: "freelancer.png",
            desc: "Développeur web Full-Stack Freelancer & Upwork, Internet (télétravail)",
            mission: "Mission : Développement de sites web, des applications web et mobile : - Plateformes E-commerce utilisant Opencart Cms & VueJS. - Sites Web Catalogue & Portfolio Utilisant Wordpress Cms & VueJS. - Application web et mobile utilisant React JS & React Native + Api utilisant Laravel 8 & Livewire 2 & Tailwindcss & AlpineJs.",
            date: "2019 - 2021",
        },
        {
            logo: "flegri.png",
            desc: "Développeur web Full-Stack chez Flegrei, Moscou, Russie",
            mission: "Mission : Développement de sites web, des applications web et mobile : - Plateformes E-commerce utilisant Opencart Cms. - Sites Web Catalogue & Portfolio Utilisant Wordpress Cms. - Application mobile utlisant Ionic-framework & Angular Js + Api utilisant Laravel 7.",
            date: "2019 - 2021",
        },
        {
            logo: "kvantum.png",
            desc: "Développeur web Full-Stack chez Kvantum, Moscou, Russie (télétravail)",
            mission: "Mission : Développement de sites web, des applications web et mobile : - Plateformes E-commerce utilisant Opencart Cms. - •	Sites Web Catalogue & Portfolio Utilisant Joomla Cms. - •	Application web Utilisant Laravel 7.",
            date: "2019 - 2021",
        },
        {
            logo: "ksar.png",
            desc: "Administrateur de système chez l'Hôtel LTI El Ksar, Sousse, Tunisie.",
            mission: "Mission :  Gestion et maintenance de parc informatique, réseau local et wifi, téléphonie, caméras de surveillance, système ERP et 1er responsable audiovisuelles.",
            date: "2013 - 2018",
        },
        {
            logo: "steq.png",
            desc: "Développeur logiciels chez la société Tunisienne des équipements, Tunis, Tunisie.",
            mission: "Mission : Développement du système ERP de la société utilisant Foxpro.",
            date: "2011 - 2012",
        },
    ],
    skills: [
        {
            groupName: "Base Skills",
            groupSkills: [
                "html.png",
                "css.png",
                "js.png",
                "php.png",
                "mysql.png",
            ]
        },
        {
            groupName: "Css Skills",
            groupSkills: [
                "sass.png",
                "tailwindcss.png",
                "alpinejs.png",
                "jquery.png",
                "bootstrap.png",
            ]
        },
        {
            groupName: "Front-end Skills",
            groupSkills: [
                "reactjs.png",
                "next.png",
                "vuejs.png",
                "reactnative.png",
                "ionic.png",
            ]
        },
        {
            groupName: "Back-end Skills",
            groupSkills: [
                "laravel.png",
                "nodejs.png",
                "wordpress.png",
                "opencart.png",
                "joomla.png",
            ]
        },
        {
            groupName: "Mern-Stack Skills",
            groupSkills: [
                "express.png",
                "mongodb.png",
                "redux.png",
                "materialui.png",
                "heroku.png",
            ]
        },
        
    ],
    portfolio: [
        {
            name: "Iber Conseils",
            photo: "iber.png",
            code: "https://github.com/MaamounGrissa/iber.git",
            url: "https://iber-conseils.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "KineDoc",
            photo: "kinedoc.png",
            code: "https://github.com/MaamounGrissa/kinedoc.git",
            url: "https://kinedocrdv.fr/",
            skills: ["reactjs", "nodejs"],
        },
        /* {
            name: "Arine Conseils",
            photo: "arine.png",
            code: "https://github.com/MaamounGrissa/aca-next.git",
            url: "https://arine-conseils.com/",
            skills: ["next", "css"],
        }, */
        {
            name: "Anytime & Anywhere",
            photo: "anytime.png",
            code: "https://github.com/MaamounGrissa/Anytime4Anywhere.git",
            url: "https://anytime4anywhere.com/",
            skills: ["reactjs", "css"],
        },
        {
            name: "Belkhairat Trading",
            photo: "bk-trading.png",
            code: "https://github.com/MaamounGrissa",
            url: "https://belkhairat-trading.com/",
            skills: ["opencart", "php"],
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            code: "",
            url: "https://vw.autodomkst.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            code: "https://github.com/MaamounGrissa/Valorant-Boosting.git",
            url: "https://valorantboosting.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            code: "https://github.com/MaamounGrissa/dnl",
            url: "https://dnl-deco.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            code: "https://github.com/MaamounGrissa/dalimarket",
            url: "https://dalimarket.tn/",
            skills: ["opencart", "tailwindcss"],
        },
        {
            name: "My Portfolio App",
            photo: "myportfolio.png",
            code: "https://github.com/MaamounGrissa/maamoun-portfolio-app",
            url: "https://maamoungrissa.me/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            code: "",
            url: "https://pro-artl.ru/",
            skills: ["opencart", "php"],
        },
        {
            name: "BJMatrix Store App",
            photo: "bjmatrix.png",
            code: "https://github.com/MaamounGrissa/bjmatrix.git",
            url: "https://bjmatrix.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Conformit App",
            photo: "conformit-vuejs.png",
            code: "https://github.com/MaamounGrissa/Conformit.git",
            url: "https://conformit-vuejs.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Wearmoon App",
            photo: "wearmoon-reactjs.png",
            code: "https://github.com/MaamounGrissa/WearMoon",
            url: "https://wearmoon-reactjs.netlify.app/",
            skills: ["reactjs", "sass"],
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            code: "https://github.com/MaamounGrissa/autodomkst",
            url: "",
            skills: ["laravel", "mysql"],
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            code: "",
            url: "https://barrist.ru/",
            skills: ["wordpress", "css"],
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            code: "",
            url: "https://volkswagen-almaty.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            code: "",
            url: "https://retail.comiten.ru/",
            skills: ["joomla", "html"],
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            code: "",
            url: "https://www.zavodskaya-plitka.ru/",
            skills: ["joomla", "css"],
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            code: "https://github.com/MaamounGrissa/Aidapraznik2020",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
            skills: ["html","jquery"],
        },
        {
            name: "Flegrei",
            photo: "flegri.png",
            code: "",
            url: "https://www.flegri.com/",
            skills: ["opencart", "html"],
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            code: "",
            url: "https://bahitgul.com/",
            skills: ["wordpress", "html"],
        },
    ],

    // Template Titles
    download_link: "Télécharger le CV en PDF",
    education_title: "Éducation",
    experience_title: "Expérience",
    skills_title: "Compétences",
    portfolio_title: "Portefeuille",
    url_btn: "Lien",
    code_btn: "Code",
    contact_heading: "Envoyez moi un message !",
    name_label: "Nom",
    email_label: "E-mail",
    message_label: "Message",
    send_btn: "Envoyer",
    feedback_message: "Message envoyé avec succès !",
    error_message: "Erreur ! Veuillez réessayer plus tard !",
}

export const ru = {
    lang: "ru",
    name: "Маамун Грисса",
    job: "Веб-Разработчик Полного Стека",
    age: 33,
    phone: "+21650870256",
    email: "grissa.maamoun@gmail.com",
    intro: "Инновационный веб-разработчик полного стека с 4-летним опытом работы в разработке и кодировании веб-сайтов, веб-приложений и мобильных приложений. Продемонстрированный талант к интерфейсной и серверной веб-разработке для оптимизации присутствия в Интернете. Опытный эксперт в HTML, CSS, JavaScript, PHP, MySQL, MongoDB, NodeJS, ReactJS, NextJs, Vue Js, React Native, Ionic Framework ...",
    linkedin: "maamoun-grissa",
    facebook: "maamoung",
    instagram: "gmaamoun",
    cv: "MaamounGrissa-Resume-Fevrier22-EN.pdf",
    education: [
        {
            logo: "iset.jpg",
            certificate: "Прикладная лицензия в мультимедиа и веб-разработке",
            institute: "Высший институт технологических исследований, Сусс, Тунис",
            date: "2007 - 2011",
        },
        {
            logo: "iset.jpg",
            certificate: "Сертификат Cisco : нетворкинг для дома и малого бизнеса",
            institute: "Высший институт технологических исследований, Сусс, Тунис",
            date: "2009 - 2010",
        },
    ],
    experience: [
        {
            logo: "squadio.png",
            desc: "Разработчик веб-приложений Frontend, Squadio, Саудовская Аравия (Удаленный)",
            mission: "Обязанности:  Разработка и поддержка веб-приложений - React js - Redux - Laravel ...",
            date: "2021 - Сегодня",
        },
        {
            logo: "anytime.png",
            desc: "Менеджер в Anytime & Anywhere",
            mission: "Услуги: Разработка статических веб-сайтов, платформ электронной коммерции, веб-приложений и мобильных приложений, Графический дизайн, Фирменный стиль компаний, Цифровой маркетинг, SEO ...",
            date: "2021 - Сегодня",
        },        
        {
            logo: "freelancer.png",
            desc: "Веб-разработчик Full-Stack, Freelancer & Upwork , Интернет (Удаленный)",
            mission: "Обязанности: Разработка веб-сайтов, веб-и мобильных приложений : - Платформы электронной коммерции с использованием opencart cms и Vue JS. - Каталог и портфолио веб-сайтов с Wordpress CMS и Vue JS. - Веб-и мобильное приложение с React JS и React Native + Api с Laravel 8 & Livewire 2 & Tailwindcss & Alpine.",
            date: "2019 - 2021",
        },
        {
            logo: "flegri.png",
            desc: "Веб-разработчик Full-Stack, Флегрей, Москва, Россия",
            mission: "Обязанности: Разработка веб-сайтов, веб-и мобильных приложений : - Платформы электронной коммерции с использованием opencart cms. - Каталог и портфолио веб-сайтов с Wordpress CMS. - Мобильное приложение с Ionic-framework и Angular Js + Api с Laravel 7.",
            date: "2019 - 2021",
        },
        {
            logo: "kvantum.png",
            desc: "Веб-разработчик Full-Stack, Квантум, Москва, Россия (Удаленный)",
            mission: "Обязанности: Разработка веб-сайтов, веб-и мобильных приложений : - Каталог и портфолио веб-сайтов с Joomla CMS. - Веб приложение с Laravel 7.",
            date: "2019 - 2021",
        },
        {
            logo: "ksar.png",
            desc: "Системный администратор в отеле LTI El Ksar, Сусс, Тунис.",
            mission: "Обязанности : Управление и техническое обслуживание компьютерного оборудования, локальных сетей, сетей Wi-Fi, телефонии, камер наблюдения, ERP-системы и аудиовизуального менеджера.",
            date: "2013 - 2018",
        },
        {
            logo: "steq.png",
            desc: "Разработчик программного обеспечения в тунисской компании оборудования, Тунис, Тунис.",
            mission: "Обязанности : Разработка программного обеспечения ERP с FoxPro.",
            date: "2011 - 2012",
        },
    ],
    skills: [
        {
            groupName: "Base Skills",
            groupSkills: [
                "html.png",
                "css.png",
                "js.png",
                "php.png",
                "mysql.png",
            ]
        },
        {
            groupName: "Css Skills",
            groupSkills: [
                "sass.png",
                "tailwindcss.png",
                "alpinejs.png",
                "jquery.png",
                "bootstrap.png",
            ]
        },
        {
            groupName: "Front-end Skills",
            groupSkills: [
                "reactjs.png",
                "next.png",
                "vuejs.png",
                "reactnative.png",
                "ionic.png",
            ]
        },
        {
            groupName: "Back-end Skills",
            groupSkills: [
                "laravel.png",
                "nodejs.png",
                "wordpress.png",
                "opencart.png",
                "joomla.png",
            ]
        },
        {
            groupName: "Mern-Stack Skills",
            groupSkills: [
                "express.png",
                "mongodb.png",
                "redux.png",
                "materialui.png",
                "heroku.png",
            ]
        },
        
    ],
    portfolio: [
        {
            name: "Iber Conseils",
            photo: "iber.png",
            code: "https://github.com/MaamounGrissa/iber.git",
            url: "https://iber-conseils.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "KineDoc",
            photo: "kinedoc.png",
            code: "https://github.com/MaamounGrissa/kinedoc.git",
            url: "https://kinedocrdv.fr/",
            skills: ["reactjs", "nodejs"],
        },
        /* {
            name: "Arine Conseils",
            photo: "arine.png",
            code: "https://github.com/MaamounGrissa/aca-next.git",
            url: "https://arine-conseils.com/",
            skills: ["next", "css"],
        }, */
        {
            name: "Anytime & Anywhere",
            photo: "anytime.png",
            code: "https://github.com/MaamounGrissa/Anytime4Anywhere.git",
            url: "https://anytime4anywhere.com/",
            skills: ["reactjs", "css"],
        },
        {
            name: "Belkhairat Trading",
            photo: "bk-trading.png",
            code: "https://github.com/MaamounGrissa",
            url: "https://belkhairat-trading.com/",
            skills: ["opencart", "php"],
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            code: "",
            url: "https://vw.autodomkst.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            code: "https://github.com/MaamounGrissa/Valorant-Boosting.git",
            url: "https://valorantboosting.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            code: "https://github.com/MaamounGrissa/dnl",
            url: "https://dnl-deco.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            code: "https://github.com/MaamounGrissa/dalimarket",
            url: "https://dalimarket.tn/",
            skills: ["opencart", "tailwindcss"],
        },
        {
            name: "My Portfolio App",
            photo: "myportfolio.png",
            code: "https://github.com/MaamounGrissa/maamoun-portfolio-app",
            url: "https://maamoungrissa.me/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            code: "",
            url: "https://pro-artl.ru/",
            skills: ["opencart", "php"],
        },
        {
            name: "BJMatrix Store App",
            photo: "bjmatrix.png",
            code: "https://github.com/MaamounGrissa/bjmatrix.git",
            url: "https://bjmatrix.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Conformit App",
            photo: "conformit-vuejs.png",
            code: "https://github.com/MaamounGrissa/Conformit.git",
            url: "https://conformit-vuejs.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Wearmoon App",
            photo: "wearmoon-reactjs.png",
            code: "https://github.com/MaamounGrissa/WearMoon",
            url: "https://wearmoon-reactjs.netlify.app/",
            skills: ["reactjs", "sass"],
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            code: "https://github.com/MaamounGrissa/autodomkst",
            url: "",
            skills: ["laravel", "mysql"],
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            code: "",
            url: "https://barrist.ru/",
            skills: ["wordpress", "css"],
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            code: "",
            url: "https://volkswagen-almaty.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            code: "",
            url: "https://retail.comiten.ru/",
            skills: ["joomla", "html"],
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            code: "",
            url: "https://www.zavodskaya-plitka.ru/",
            skills: ["joomla", "css"],
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            code: "https://github.com/MaamounGrissa/Aidapraznik2020",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
            skills: ["html","jquery"],
        },
        {
            name: "Flegrei",
            photo: "flegri.png",
            code: "",
            url: "https://www.flegri.com/",
            skills: ["opencart", "html"],
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            code: "",
            url: "https://bahitgul.com/",
            skills: ["wordpress", "html"],
        },
    ],

    // Template Titles
    download_link: "Скачать резюме в формате PDF",
    education_title: "Образование",
    experience_title: "Опыт",
    skills_title: "Навыки",
    portfolio_title: "Портфолио",
    url_btn: "Ссылка",
    code_btn: "Код",
    contact_heading: "Отправь мне сообщение !",
    name_label: "Имя",
    email_label: "Эл. адрес",
    message_label: "Сообщение",
    send_btn: "Отправить",
    feedback_message: "Сообщение успешно отправлено !",
    error_message: "Ошибка ! Пожалуйста, повторите попытку позже !",
    
}

export const ar = {
    lang: "ar",
    name: "المأمون قريسة",
    job: "مبرمج واب",
    age: 33,
    phone: "+21650870256",
    email: "grissa.maamoun@gmail.com",
    intro: "مطور ومبرمج ويب مبتكر Full Stack يتمتع بخبرة 4 سنوات في برمجة مواقع الويب وتصميم تطبيقات الويب والجوال. موهبة ثابة في تطوير الويب لتحسين التواجد عبر الإنترنت. خبير متمرس في HTML، CSS، JavaScript، PHP، MySQL، MongoDB، NodeJs، ReactJs, NextJs، VueJs، ReactNative، Ionic Framework ...",
    linkedin: "maamoun-grissa",
    facebook: "maamoung",
    instagram: "gmaamoun",
    cv: "MaamounGrissa-Resume-Fevrier22-EN.pdf",
    education: [
        {
            logo: "iset.jpg",
            certificate: "الاجازة التطبيقة في تكنولوجيا الاعلامية اختصاص تطوير الويب",
            institute: "المعهد العالي للدراسات التكنولوجية بسوسة، تونس",
            date: "2007 - 2011",
        },
        {
            logo: "iset.jpg",
            certificate: "شهادة سيسكو : شبكات المنازل والشركات الصغيرة",
            institute: "المعهد العالي للدراسات التكنولوجية بسوسة، تونس",
            date: "2009 - 2010",
        },
    ],
    experience: [
        {
            logo: "squadio.png",
            desc: "مبرمج واب بشركة ابتكار، (عن بعد)",
            mission: "المهمة: برمجة و تتطوير المواقع و برمجيات الواب",
            date: "2021 - اليوم",
        },
        {
            logo: "anytime.png",
            desc: "مدير بشركة Anytime & Anywhere",
            mission: "الخدمات: تطوير مواقع الويب، منصات التجارة الإلكترونية ، تطبيقات الويب والهاتف، التصميم الجرافيكي ، هوية الشركات ، التسويق الرقمي ، تحسين محركات البحث ...",
            date: "2021 - اليوم",
        },
        {
            logo: "freelancer.png",
            desc: "مبرمج واب حر، الانترنت (عن بعد)",
            mission: "المهمة: برمجة و تتطوير المواقع و برمجيات الواب و الهاتف : تطوير و برمجة مواقع للتجارة الالكترونية و المواقع والتطبيقات الخاصة بالأفراد و الشركات",
            date: "2019 - 2021",
        },
        {
            logo: "flegri.png",
            desc: "مبرمج واب بشركة فلقراي، موسكو، روسيا",
            mission: "المهمة: برمجة و تتطوير المواقع و برمجيات الواب و الهاتف : تطوير و برمجة مواقع للتجارة الالكترونية و المواقع والتطبيقات الخاصة بالأفراد و الشركات",
            date: "2019 - 2021",
        },
        {
            logo: "kvantum.png",
            desc: "مبرمج واب بشركة كفانتوم، موسكو، روسيا (عن بعد)",
            mission: "المهمة: برمجة و تتطوير المواقع و برمجيات الواب و الهاتف : تطوير و برمجة مواقع للتجارة الالكترونية و المواقع والتطبيقات الخاصة بالأفراد و الشركات",
            date: "2019 - 2021",
        },
        {
            logo: "ksar.png",
            desc: "مدير نظام المعلوماتيات بنزل القصر، سوسة، تونس",
            mission: "المهمة: إدارة وصيانة أجهزة الكمبيوتر والشبكات المحلية وشبكات الواي فاي والهواتف وكاميرات المراقبة ونظام تخطيط موارد المؤسسات ومدير الصوتيات والمرئيات.",
            date: "2013 - 2018",
        },
        {
            logo: "steq.png",
            desc: "مبرمج بالشركة التونسية للمعدات، تونس، تونس",
            mission: "المهمة: برمجة و تتطوير النظام الخاص بالشركة",
            date: "2011 - 2012",
        },
    ],
    skills: [
        {
            groupName: "Base Skills",
            groupSkills: [
                "html.png",
                "css.png",
                "js.png",
                "php.png",
                "mysql.png",
            ]
        },
        {
            groupName: "Css Skills",
            groupSkills: [
                "sass.png",
                "tailwindcss.png",
                "alpinejs.png",
                "jquery.png",
                "bootstrap.png",
            ]
        },
        {
            groupName: "Front-end Skills",
            groupSkills: [
                "reactjs.png",
                "next.png",
                "vuejs.png",
                "reactnative.png",
                "ionic.png",
            ]
        },
        {
            groupName: "Back-end Skills",
            groupSkills: [
                "laravel.png",
                "nodejs.png",
                "wordpress.png",
                "opencart.png",
                "joomla.png",
            ]
        },
        {
            groupName: "Mern-Stack Skills",
            groupSkills: [
                "express.png",
                "mongodb.png",
                "redux.png",
                "materialui.png",
                "heroku.png",
            ]
        },
        
    ],
    portfolio: [
        {
            name: "Iber Conseils",
            photo: "iber.png",
            code: "https://github.com/MaamounGrissa/iber.git",
            url: "https://iber-conseils.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "KineDoc",
            photo: "kinedoc.png",
            code: "https://github.com/MaamounGrissa/kinedoc.git",
            url: "https://kinedocrdv.fr/",
            skills: ["reactjs", "nodejs"],
        },
        /* {
            name: "Arine Conseils",
            photo: "arine.png",
            code: "https://github.com/MaamounGrissa/aca-next.git",
            url: "https://arine-conseils.com/",
            skills: ["next", "css"],
        }, */
        {
            name: "Anytime & Anywhere",
            photo: "anytime.png",
            code: "https://github.com/MaamounGrissa/Anytime4Anywhere.git",
            url: "https://anytime4anywhere.com/",
            skills: ["reactjs", "css"],
        },
        {
            name: "Belkhairat Trading",
            photo: "bk-trading.png",
            code: "https://github.com/MaamounGrissa",
            url: "https://belkhairat-trading.com/",
            skills: ["opencart", "php"],
        },
        {
            name: "Volkswagen Costanai",
            photo: "volkswagen-costanai.png",
            code: "",
            url: "https://vw.autodomkst.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Valorant Boosting",
            photo: "valorant.png",
            code: "https://github.com/MaamounGrissa/Valorant-Boosting.git",
            url: "https://valorantboosting.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "DNL Deco",
            photo: "dnl.png",
            code: "https://github.com/MaamounGrissa/dnl",
            url: "https://dnl-deco.herokuapp.com/",
            skills: ["reactjs", "nodejs"],
        },
        {
            name: "Dali Market",
            photo: "dalimarket.png",
            code: "https://github.com/MaamounGrissa/dalimarket",
            url: "https://dalimarket.tn/",
            skills: ["opencart", "tailwindcss"],
        },
        {
            name: "My Portfolio App",
            photo: "myportfolio.png",
            code: "https://github.com/MaamounGrissa/maamoun-portfolio-app",
            url: "https://maamoungrissa.me/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Pro Artl",
            photo: "pro-artl.png",
            code: "",
            url: "https://pro-artl.ru/",
            skills: ["opencart", "php"],
        },
        {
            name: "BJMatrix Store App",
            photo: "bjmatrix.png",
            code: "https://github.com/MaamounGrissa/bjmatrix.git",
            url: "https://bjmatrix.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Conformit App",
            photo: "conformit-vuejs.png",
            code: "https://github.com/MaamounGrissa/Conformit.git",
            url: "https://conformit-vuejs.netlify.app/",
            skills: ["vuejs", "css"],
        },
        {
            name: "Wearmoon App",
            photo: "wearmoon-reactjs.png",
            code: "https://github.com/MaamounGrissa/WearMoon",
            url: "https://wearmoon-reactjs.netlify.app/",
            skills: ["reactjs", "sass"],
        },
        {
            name: "Auto Dom Kst",
            photo: "autodomkst.png",
            code: "https://github.com/MaamounGrissa/autodomkst",
            url: "",
            skills: ["laravel", "mysql"],
        },
        {
            name: "Barrist",
            photo: "barrist.png",
            code: "",
            url: "https://barrist.ru/",
            skills: ["wordpress", "css"],
        },
        {
            name: "Volkswagen Almaty",
            photo: "volkswagen-almaty.png",
            code: "",
            url: "https://volkswagen-almaty.kz/",
            skills: ["joomla", "sass"],
        },
        {
            name: "Retail Comiten",
            photo: "retail-comiten.png",
            code: "",
            url: "https://retail.comiten.ru/",
            skills: ["joomla", "html"],
        },
        {
            name: "Zavodskaya Plitka",
            photo: "zavodskaya-plitka.png",
            code: "",
            url: "https://www.zavodskaya-plitka.ru/",
            skills: ["joomla", "css"],
        },
        {
            name: "Aidapraznik",
            photo: "aidapraznik.png",
            code: "https://github.com/MaamounGrissa/Aidapraznik2020",
            url: "http://www.aidaprazdnik-dedmoroz.ru/",
            skills: ["html","jquery"],
        },
        {
            name: "Flegrei",
            photo: "flegri.png",
            code: "",
            url: "https://www.flegri.com/",
            skills: ["opencart", "html"],
        },
        {
            name: "Bahitgul Hotel",
            photo: "bahitgul.png",
            code: "",
            url: "https://bahitgul.com/",
            skills: ["wordpress", "html"],
        },
    ],

    // Template Titles
    download_link: 'تحميل السيرة الذاتية',
    education_title: "الشهادات",
    experience_title: "الخبرات",
    skills_title: "المهارات",
    portfolio_title: "الانجازات",
    url_btn: "الرابط",
    code_btn: "الكود",
    contact_heading: "أرسل لي رسالة",
    name_label: "الاسم",
    email_label: "البريد الالكتروني",
    message_label: "الرسالة",
    send_btn: "أرسل",
    feedback_message: "تم ارسال الرسالة بنجاح",
    error_message: "خطأ ! الرجاء إعادة المحاولة في وقت لاحق",
}